### ISSUE TITLE
Add a ticking sound by default

### ISSUE THREAD

**Issue by maikol-solis** [SqrtMinusOne/pomm.el#2]
Testing the package, I noticed that it doesn't have a ticking sound by default. 

Other packages like org-pomodoro includes it directly in their repository (https://github.com/marcinkoziej/org-pomodoro/tree/master/resources). 

Maybe it could be a good idea to have the whole set of features by default and let the user remove them if they don't want them. 

Best.

**Comment by SqrtMinusOne** [comment]
Well, the ticking sound as a default option seems a bit too intrusive to me, but I guess I'll add sounds in the next version.

There is a slight problem that it's hard to make this functionality platform-agnostic, as it will certainly depend on some player binary installed, and there are lots of them.

Meanwhile, as you seem to be using OS X, I guess you can do something like
```lisp
(add-hook 'pomm-on-tick-hook
          (lambda () (call-process "afplay" nil nil nil "path/to/your/tick.mp3")))
```

**Comment by maikol-solis** [comment]
Fair enough. You're right about the binaries in the different OSes. Thanks again. 

Just for the record, the command that worked for me was 

```
(add-hook 'pomm-on-tick-hook
            (lambda () (start-process-shell-command "tick" nil "afplay ~/.doom.d/tick.wav")))
```

(copied from here https://github.com/marcinkoziej/org-pomodoro/blob/master/org-pomodoro.el#L420)

**Comment by maikol-solis** [comment]
I tweaked a little the hook to avoid any sounds in the breaks. 

``` elisp
(add-hook 'pomm-on-tick-hook
            (lambda ()
              (if (eq (alist-get 'kind (alist-get 'current pomm--state)) 'work)
                  (start-process-shell-command "tick" nil "afplay ~/.doom.d/tick.wav")
                nil)))
```

**Comment by SqrtMinusOne** [comment]
Added sounds as well.

Until (and if, hopefully) the MELPA recipe is updated, you'd have to include the resources folder to the package recipe yourself, like I mentioned in the [README](https://github.com/SqrtMinusOne/pomm.el#installation). Or set your own files in the `pomm-audio-files` variable.

**Comment by maikol-solis** [comment]
Thank you very much! 

~~I think you can adjust [your recipe](https://github.com/melpa/melpa/blob/master/recipes/pomm), to add the sounds files directly from MELPA (easier for users in doom or spacemacs)~~


~~(pomm 
:repo "SqrtMinusOne/pomm.el" 
:fetcher github
 :files (:defaults "resources"))~~


I just noticed your PR in MELPA https://github.com/melpa/melpa/pull/7794. Sorry for the noise. 

 Best.

**Comment by SqrtMinusOne** [comment]
Should work by now.
