### ISSUE TITLE
[REQUEST] Link the current timer to some task to add more context

### ISSUE THREAD

**Issue by maikol-solis** [SqrtMinusOne/pomm.el#5]
One feature in org-pomodoro is to run the timer over a specific task. 

Your package can run the timer without this constraint, but it misses the context. 

For example, imagine you have a task in a file inside your `org-directory`  

```
* TODO My important task
```

It would be nice if, when the cursor is over the heading, launching `pomm-start` the task automatically stays linked to current timer. 

Therefore, in the csv it could appear something like this 

```
timestamp, status,period,iteration,context
1636221045,running,work,1,"My important task"
```

Another option is to ask the user what tasks do you want to link the current timer according to the task in the `org-directory`. 

I'm not clear about what could be the best (and easier) way to implement it, but this is the idea. 

Best.

**Comment by SqrtMinusOne** [comment]
Hmm, that does sound like org-pomodoro. It may be possible to integrate this with `org-clock-in`, and then this package will become basically a superset of org-pomodoro.

I'll see what I can do, probably not quite in the nearest future, but I do want to try this idea.

**Comment by maikol-solis** [comment]
Yes it sound like `org-pomodoro` but it doesn't. With org-pomodoro you are forced to start the time from a task and the timestamps stay in the `LOGBOOK` of each task. If you want to collect those, you need to do something extra. Also, once the task is archived, those registers are lost. 

Your implementation adds the csv file which for me is fantastic. It collects all the pomodoros info in one centralized place. 

However, the lack of context in the csv doesn't allow the users to understand in what tasks they are spending more time. Of course, we can simply write it down in a piece of paper and then add them manually to the csv. 

This is just one idea. Maybe you can figure this out better. 

Best.

**Comment by SqrtMinusOne** [comment]
Added something like what you've described in 60b74bfe9e67be59a1023f19336521bef650241c. For now decided to make a it a simple string, I'll see how this goes for me.

**Comment by maikol-solis** [comment]
Thanks! I'll try it. It seems very promising.

**Comment by SqrtMinusOne** [comment]
Feel free to reopen if some new information appears in this context.

**Comment by maikol-solis** [comment]
Sure. Thanks for all!
