### ISSUE TITLE
[REQUEST] Adding more flexibility to pomm using the third time technique. 

### ISSUE THREAD

**Issue by maikol-solis** [SqrtMinusOne/pomm.el#8]
Hi!

In my productivity experiments, I stumbled upon with this great package

https://github.com/telotortium/org-pomodoro-third-time

Basically, it uses the pomodoro principle, but using the formula 

```
Time of break =  1/3 x Time of work. 
```

Therefore, If you worked for 1 hour straight, then you can have a maximum of 20 minutes of break. Also, if you are focused in something and only used 5 minutes of your break time, the other left 15 minutes you can use them later (combined with another break) if you want a really long break (for taking a nap for example). 

The technique's full explanation: https://www.lesswrong.com/posts/RWu8eZqbwgB9zaerh/third-time-a-better-way-to-work

The magic of this is that the periods of work are completely dynamic. You can work 20 minutes, then 1 hour, then 10 minutes, etc. All depends on your day. 

I've used `org-pomodoro-third-time` and it's awesome. Obviously, it depends completely on `org-pomodoro`. 

Maybe this could be something to consider to add into `pomm` for more flexibility 

WDYT?

**Comment by SqrtMinusOne** [comment]
Thanks for sharing, it sounds interesting. Maybe it will fit my workflow better than the original pomodoro.

I'll try to implement that when I have the time.

**Comment by maikol-solis** [comment]
Super cool. Try first `org-pomodoro-third-time` to get used it to the workflow. The author did an awesome job with the package. Maybe you could steal him some ideas/code for `pomm`. 

Best.

**Comment by SqrtMinusOne** [comment]
Added, `M-x pomm-third-time` is the new entrypoint. I'll give this a more extensive test after my vacation ends.

**Comment by maikol-solis** [comment]
Thank you very much! I just tried and works awesome. Your implementation follows perfectly de the method. 

Just as comment, for me the functions `org-pomodoro-third-time-end-at` or `org-pomodoro-third-time-end-in` are super useful. Check if those are useful to you and the package. 

Again, thanks for your awesome contribution!

**Comment by snan** [comment]
It's slightly weird how it automatically assumes I successfully got back to work after the break and starts counting up work time 💁🏻‍♀️
